#!/usr/bin/env python3
"""
Generates seed.sql from data/family_book.json.
Run from the repo root: python3 scripts/generate_seed.py
Output: scripts/seed.sql
"""

import json
import uuid
from collections import deque
from pathlib import Path

DATA_PATH = Path(__file__).parent.parent / "data" / "family_book.json"
OUT_PATH = Path(__file__).parent / "seed.sql"


def sql_str(value):
    if value is None or value == "":
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def sql_bool(value):
    return "TRUE" if value else "FALSE"


def main():
    with open(DATA_PATH, encoding="utf-8") as f:
        data = json.load(f)

    family_groups = []
    all_people = []

    for family in data["families"]:
        group_id = int(family["id"])
        family_groups.append({
            "id": group_id,
            "name": family["name"],
            "spouse_name": family.get("spouse") or None,
            "deceased": family["deceased"],
            "spouse_deceased": family["spouseDeceased"],
        })

        # BFS so every parent is inserted before its children
        queue = deque()
        queue.append((family, None))

        while queue:
            node, parent_uuid = queue.popleft()
            person_uuid = str(uuid.uuid4())

            spouse = node.get("spouse") or None
            all_people.append({
                "id": person_uuid,
                "legacy_id": node["id"],
                "family_group_id": group_id,
                "parent_id": parent_uuid,
                "name": node["name"],
                "spouse_name": spouse,
                "deceased": node["deceased"],
                "spouse_deceased": node["spouseDeceased"],
            })

            for child in node.get("children", []):
                queue.append((child, person_uuid))

    lines = []
    lines.append("-- Auto-generated by scripts/generate_seed.py")
    lines.append("-- Run against your Supabase project SQL editor")
    lines.append("")

    # ── family_groups ──────────────────────────────────────────────────────
    lines.append("-- family_groups")
    lines.append("INSERT INTO family_groups (id, name, spouse_name, deceased, spouse_deceased) VALUES")
    group_rows = []
    for g in family_groups:
        group_rows.append(
            f"  ({g['id']}, {sql_str(g['name'])}, {sql_str(g['spouse_name'])}, "
            f"{sql_bool(g['deceased'])}, {sql_bool(g['spouse_deceased'])})"
        )
    lines.append(",\n".join(group_rows) + ";")
    lines.append("")

    # ── people ─────────────────────────────────────────────────────────────
    lines.append("-- people (BFS order ensures parent rows precede child rows)")
    lines.append("INSERT INTO people")
    lines.append("  (id, legacy_id, family_group_id, parent_id, name, spouse_name, deceased, spouse_deceased)")
    lines.append("VALUES")

    person_rows = []
    for p in all_people:
        parent_val = sql_str(p["parent_id"]) if p["parent_id"] else "NULL"
        # Cast UUIDs explicitly so Postgres accepts the string literals
        id_val = f"'{p['id']}'::uuid"
        parent_val = f"'{p['parent_id']}'::uuid" if p["parent_id"] else "NULL"
        person_rows.append(
            f"  ({id_val}, {sql_str(p['legacy_id'])}, {p['family_group_id']}, {parent_val}, "
            f"{sql_str(p['name'])}, {sql_str(p['spouse_name'])}, "
            f"{sql_bool(p['deceased'])}, {sql_bool(p['spouse_deceased'])})"
        )

    lines.append(",\n".join(person_rows) + ";")
    lines.append("")
    lines.append(f"-- Inserted {len(family_groups)} family groups and {len(all_people)} people.")

    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Done. {len(all_people)} people written to {OUT_PATH}")


if __name__ == "__main__":
    main()
